#Taken from https://www.playstationtrophies.org/forum/topic/163466-wheel-of-fortune-answer-list/
# puzzles.py

PUZZLES = [
    # Category: People / Occupations
    {"category": "Person", "puzzle": "OLD FRIEND"},
    {"category": "Person", "puzzle": "PLATOON LEADER"},
    {"category": "Person", "puzzle": "PUBLIC SPEAKER"},
    {"category": "Person", "puzzle": "SCHOOL COUNSELOR"},
    {"category": "Person", "puzzle": "SOUTHPAW"},
    {"category": "Person", "puzzle": "SENIOR OFFICIAL"},
    {"category": "Person", "puzzle": "STAGE MOTHER"},
    {"category": "Person", "puzzle": "STAR PERFORMER"},
    {"category": "Person", "puzzle": "SPEAKER OF THE HOUSE"},
    {"category": "Person", "puzzle": "STEADY BOYFRIEND"},
    {"category": "Person", "puzzle": "TRAINED ATHLETE"},
    {"category": "Person", "puzzle": "WOODCARVER"},
    {"category": "Person", "puzzle": "WET BLANKET"},

    # Category: Phrase
    {"category": "Phrase", "puzzle": "A GOOD FIT"},
    {"category": "Phrase", "puzzle": "A GREAT BUY"},
    {"category": "Phrase", "puzzle": "AHEAD OF THE GAME"},
    {"category": "Phrase", "puzzle": "ALL OPERATORS ARE BUSY"},
    {"category": "Phrase", "puzzle": "AS RED AS A BEET"},
    {"category": "Phrase", "puzzle": "AVOID THE PITFALLS"},
    {"category": "Phrase", "puzzle": "A GRIPPING PAGE TURNER"},
    {"category": "Phrase", "puzzle": "BACK TO BASICS"},
    {"category": "Phrase", "puzzle": "BONJOUR!"},
    {"category": "Phrase", "puzzle": "CULTURAL CENTER OF THE COUNTRY"},
    {"category": "Phrase", "puzzle": "DRAWING A BLANK"},
    {"category": "Phrase", "puzzle": "DON'T SPOIL YOUR DINNER"},
    {"category": "Phrase", "puzzle": "FALL IN LOVE WITH THIS CITY"},
    {"category": "Phrase", "puzzle": "GIVE ME A HINT"},
    {"category": "Phrase", "puzzle": "HAVING A GREEN THUMB"},
    {"category": "Phrase", "puzzle": "I'VE GOT A HUNCH"},
    {"category": "Phrase", "puzzle": "IT'S A DIRTY SHAME"},
    {"category": "Phrase", "puzzle": "NEVER SAY NEVER"},
    {"category": "Phrase", "puzzle": "ONCE IN A BLUE MOON"},
    {"category": "Phrase", "puzzle": "RAISING CAIN"},
    {"category": "Phrase", "puzzle": "SOME ASSEMBLY REQUIRED"},
    {"category": "Phrase", "puzzle": "THE TRUTH SHALL SET YOU FREE"},
    {"category": "Phrase", "puzzle": "WORK SMARTER NOT HARDER"},

    # Category: Place
    {"category": "Place", "puzzle": "ALOHA STATE"},
    {"category": "Place", "puzzle": "AMAZON RAIN FOREST"},
    {"category": "Place", "puzzle": "ART MUSEUM"},
    {"category": "Place", "puzzle": "BUSTLING CITY"},
    {"category": "Place", "puzzle": "CAMP GROUND"},
    {"category": "Place", "puzzle": "CITY THAT'S A PLEASURE FOR EVERYONE"},
    {"category": "Place", "puzzle": "FACTORY OUTLET MALL"},
    {"category": "Place", "puzzle": "GOLF CLUBHOUSE"},
    {"category": "Place", "puzzle": "LUSH GREEN FOREST"},
    {"category": "Place", "puzzle": "THE CAPITAL OF ITALY"},
    {"category": "Place", "puzzle": "THE WEST WING"},
    {"category": "Place", "puzzle": "VIDEO ARCADE"},
    {"category": "Place", "puzzle": "WHITE SAND BEACH"},

    # Category: Proper Name
    {"category": "Proper Name", "puzzle": "AIR FORCE ONE"},
    {"category": "Proper Name", "puzzle": "BEN AFFLECK"},
    {"category": "Proper Name", "puzzle": "BILL OF RIGHTS"},
    {"category": "Proper Name", "puzzle": "BUZZ ALDRIN"},
    {"category": "Proper Name", "puzzle": "ELI MANNING"},
    {"category": "Proper Name", "puzzle": "MICHELLE OBAMA"},
    {"category": "Proper Name", "puzzle": "MONA LISA"},
    {"category": "Proper Name", "puzzle": "PRINCE HARRY"},
    {"category": "Proper Name", "puzzle": "SAN FRANCISCO GIANTS"},
    {"category": "Proper Name", "puzzle": "THE ROLLING STONES"},
    {"category": "Proper Name", "puzzle": "U.S. AIR FORCE ACADEMY"},

    # Category: Thing
    {"category": "Thing", "puzzle": "A FRIENDLY REMINDER"},
    {"category": "Thing", "puzzle": "AMERICAN FLAG"},
    {"category": "Thing", "puzzle": "ARCHERY"},
    {"category": "Thing", "puzzle": "BOOKMARK"},
    {"category": "Thing", "puzzle": "CHAINSaw"},
    {"category": "Thing", "puzzle": "COLOR PRINTER"},
    {"category": "Thing", "puzzle": "DAZZLING NIGHTLIFE"},
    {"category": "Thing", "puzzle": "FINE DINING"},
    {"category": "Thing", "puzzle": "GOOD LUCK CHARM"},
    {"category": "Thing", "puzzle": "HD DIGITAL CAMERA"},
    {"category": "Thing", "puzzle": "LIFE SAVINGS"},
    {"category": "Thing", "puzzle": "MAGAZINE ARTICLE"},
    {"category": "Thing", "puzzle": "PERFECT REPORT CARD"},
    {"category": "Thing", "puzzle": "RADIO STATION"},
    {"category": "Thing", "puzzle": "SPARKLING SKYLINE"},
    {"category": "Thing", "puzzle": "WOODEN TOY BOX"},

    # Category: Title
    {"category": "Title", "puzzle": "A CHRISTMAS CAROL"},
    {"category": "Title", "puzzle": "ALICE'S ADVENTURES IN WONDERLAND"},
    {"category": "Title", "puzzle": "ALL THAT JAZZ"},
    {"category": "Title", "puzzle": "ROLLING STONE MAGAZINE"},
    {"category": "Title", "puzzle": "THE THREE LITTLE PIGS"},

    # Category: TV Show Title
    {"category": "TV Show Title", "puzzle": "FAMILY GUY"},
    {"category": "TV Show Title", "puzzle": "HOW I MET YOUR MOTHER"},
    {"category": "TV Show Title", "puzzle": "SO YOU THINK YOU CAN DANCE"},
    {"category": "TV Show Title", "puzzle": "THE REAL HOUSEWIVES OF NEW YORK CITY"},

    # Category: What Are You Doing?
    {"category": "What Are You Doing?", "puzzle": "BUYING TACOS FROM A STREET VENDOR"},
    {"category": "What Are You Doing?", "puzzle": "COOKING FRESHLY CAUGHT FISH"},
    {"category": "What Are You Doing?", "puzzle": "DANCING IN THE SAND"},
    {"category": "What Are You Doing?", "puzzle": "ENJOYING THE VIEW FROM NOB HILL"},
    {"category": "What Are You Doing?", "puzzle": "FLYING TO A FOREIGN COUNTRY"},
    {"category": "What Are You Doing?", "puzzle": "PAINTING THE HOUSE"},
    {"category": "What Are You Doing?", "puzzle": "SHOPPING AT THE ANTIQUE FAIR"},
    {"category": "What Are You Doing?", "puzzle": "STANDING IN LINE"},
    {"category": "What Are You Doing?", "puzzle": "TAKING A DAY TRIP TO THE BEACH"},
    {"category": "What Are You Doing?", "puzzle": "WATCHING THE HOCKEY GAME"},
]
